name: cinemapedia
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  card_swiper: ^2.0.4
  dio: ^5.1.2
  easy_localization: ^3.0.2
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.7
  flutter:
    sdk: flutter
  go_router: ^7.1.1
  isar_flutter_libs: ^3.1.0+1
  isar: ^3.1.0+1
  path_provider: ^2.0.15
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/langs/
    - assets/icons/
