name: cinemapedia
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  card_swiper: ^2.0.4
  dio: ^5.1.2
  easy_localization: ^3.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_riverpod: ^2.3.6
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.7
  go_router: ^7.1.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  shared_preferences: ^2.2.0
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  build_runner: ^2.4.5
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter_launcher_icons:
  # android: "launcher_icon"
  android: true
  image_path_android: "assets/icons/app-icon-3.jpeg"
  image_path_ios: "assets/icons/app-icon-3.jpeg"
  ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/langs/
    - assets/icons/
    - assets/loader/

flutter_native_splash:
  color: "#252829"
  image: assets/icons/app-icon-3.jpeg
  color_dark: "#042a49"
  image_dark: assets/icons/app-icon-3.jpeg
  android_12:
    image: assets/icons/app-icon-3.jpeg
    color: "#252829"
  fullscreen: true
